package mrl.ambulance;

/**
 * User: Pooyad
 * Date: Feb 6, 2011
 * Time: 11:04:25 AM
 */
public enum AmbulanceStrategy {
    RANDOM,
    RANDOM_Biased,
    GREEDY,
    CAOP,
    MARKET_CENTRALIZED,
    MARKET_DISTRIBUTED,
    LEARNING,
    MARKET_CENTRALIZED_LEADER_INITIATOR,
    GROUP_BASED,
    MARKET_CENTRALIZED_LEADER_INITIATOR_WITH_LA,
    FEDERATED_COORDINATION,
    PARTITION_BASED_COORDINATION,;
}
